# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f2a672b82914bc5374ac599dc833cde6bfbeacd42d402f5dce34995d7bd5d5a6107e54f3d7963ba5cef5ad4994bf9c975a902a4b2c8e6021d5ea954ce336948

test:
  secret_key_base: e3c302f5912f23762c2acc3d8ee4a3e611cbeea946fd1fa51bbb8f004fd8fda41779608ccbba1396e088e4b569e86618fcdd30a2179c118bf40ec65f70c169a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
